wso2/financial-services-accelerator

- .github/workflows/maven.yml
> Fix GitHub Action build
**Issue link:** N/A
------
7. [x] Migration scripts written (if applicable).
8. [x] Have you followed secure coding standards in [WSO2 Secure Engineering …
> Fix GitHub Action build

- pom.xml
> This PR adds the parent project for the accelerator
------ …
> Add the parent project

- pom.xml
> This PR changes the accelerator version to a snapshot version.
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure …
> Make the accelerator version snapshot

- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/CertificateUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/java/com/wso2/openbanking/accelerator/common/test/util/CertificateUtilsTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/java/com/wso2/openbanking/accelerator/common/test/util/CommonTestUtil.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/impl/mtls/cert/validation/executor/CertRevocationValidationExecutor.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/util/CertificateValidationUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/test/java/com/wso2/openbanking/accelerator/gateway/executor/impl/mtls/cert/validation/executor/CertRevocationValidationExecutorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/token/validators/MTLSCertificateValidator.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/claims/OBDefaultOIDCClaimsCallbackHandlerTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/token/util/TestConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/token/validators/MTLSCertificateValidatorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/resources/testng.xml
> Currently we are only validating the presence of MTLS certificate for the token endpoint. Hence even if we send a expired certificate, it is accepted. With this pr, a new validator is added to validate the expiry status of the certificate
**Issue link:** https://github.com/wso2/financial-open-banking/issues/45
------
1. [x] Ran …
> MTLS certificate expiry validation for Token endpoint

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/config/OpenBankingConfigParser.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/constant/OpenBankingConstants.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyConstants.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyValidationException.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyValidationResult.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyValidationUtils.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyValidator.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/test/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyValidatorTests.java
> This PR adds an improvement to idempotency validation including the extending capability
**Issue link:** *https://github.com/wso2/financial-open-banking/issues/47*
**Doc Issue:** *https://github.com/wso2/docs-open-banking/issues/881*
**Applicable Labels:** *OB 3.0.0*
------
6. [ x Have you verified the PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?
8. [x] Have you followed secure coding standards in [WSO2 Secure Engineering …
> Improvement to Idempotency validation with extending capability

- pom.xml
- react-apps/self-care-portal/src/main/resources/findbugs-exclude.xml
> This PR changes the parent pom to wso2-5.3 to enable public jenkins releases.
------
8. [ ] Have you followed secure coding standards in [WSO2 …
> Changing parent pom version to support jenkins releases

- pom.xml
> Fixing javadoc issues in JDK 11 build

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/claims/OBDefaultOIDCClaimsCallbackHandlerTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/token/util/TestConstants.java
> Fixed Unit test issue due an expired certificate

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/pom.xml
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/eidas/certificate/extractor/common/PSPRole.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/pom.xml
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/revocation/OCSPValidator.java
- pom.xml
> Update the bouncy castle artifacts from jdk15on to jdk18on
**Issue link:** https://github.com/wso2/financial-open-banking/issues/77
------
2. [ ] Ran Dependency-check plugin and verified report for new dependencies added.
2. [ ] Ran Dependency-check plugin and verified report …
> Update bouncycastle version

- open-banking-accelerator/accelerators/ob-apim/repository/resources/apis/VRP/VRP-swagger.yaml
- open-banking-accelerator/accelerators/ob-apim/repository/resources/apis/VRP/vrp-dynamic-endpoint-insequence-3.1.9.xml
PR contains the  VRP swagger file and the vrp-dynamic-endpoint-insequence-3.1.9.xml file
------
8. [ ] Have you followed secure coding standards in …
> VRP swagger file and the insequence file

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/interceptor/OBIntrospectionDataProvider.java
**Issue links:**
https://github.com/wso2/financial-open-banking/issues/75
**Applicable Labels:** OB300, Accelerator
------
1. [ ] Built complete solution with pull request in place
2. [ ] Documented test scenarios(link available in guides). …
> Improve introspection data provider to call the configured data provider before removing internal scopes

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/internal/IdentityExtensionsServiceComponent.java
This PR decouples the jsFunctionRegistry service from the IS code base so the adaptive.sh script running could be made optional.
Find the test scenarios performed here: https://docs.google.com/spreadsheets/d/13IH18r5y6yuzPtNpgC9HmsfShTRIfiR5sBGnUkk0oJg/edit?usp=sharing
**Issue link:**
https://github.com/wso2/financial-open-banking/issues/59
**Applicable Labels:** OB300, Accelerator
------
1. [x] Built complete solution with pull request in place
7. [ ] Migration scripts …
> [OB3][Accelerator] Decouple the adaptive auth binding from the identity extension module

- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
> This is to resolve a db connection issue occurred when running the OB2 -> OB3 migration tool (CDS).
**Issue link:** *https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/501*
------
7. [ ] Migration scripts …
> [OB3] Add commit transaction statement to getConsentAmendmentHistoryData method

- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
> Currently in user validation for consent revocation, a random user id from the consent is matched against the user who is trying to revoke the consent. This PR improves this logic to consider all members of the consent instead. If there is an authorization type validation to be done for consent revocation, it should be handled at the toolkit level because authorization types are specific to each OB spec.
**Issue link:** *https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/480*
------
2. [ ] Ran checkstyle plugin with pull …
> [OB3] Consider all users of the consent when revoking

- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.dao/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/dao/ConsentCoreDAO.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.dao/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/dao/constants/ConsentMgtDAOConstants.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.dao/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/dao/impl/ConsentCoreDAOImpl.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.dao/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/dao/queries/ConsentMgtCommonDBQueries.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/ConsentCoreService.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/test/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/OBConsentMgtCoreServiceTests.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/test/java/com/wso2/openbanking/accelerator/consent/mgt/service/util/ConsentMgtServiceTestData.java
> This PR adds a method which accepts a map of mapping ids and permissions and updates existing mapping permissions in the OB_CONSENT_MAPPING table
**Issue link:** *https://github.com/wso2/financial-open-banking/issues/93*
------
2. [ ] Ran Dependency-check plugin and verified …
> [OB3] Add a method to update account mapping permissions

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/pom.xml
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/utils/ValidatorUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/validationgroups/ValidationOrder.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/auth/extensions/authz/request/OBOAuthAuthzRequestTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/auth/extensions/response/handler/ResponseTypeHandlerTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/dcr/validation/AlgorithmValidatorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/dcr/validation/IssuerValidatorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/dcr/validation/RequiredParamsValidatorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/resources/testng.xml
> This PR will make the accelerator use the old validation classes to fix the toolkit build failures. Additional unit tests are also introduced to maintain the code coverage.
**Issue link:** *https://github.com/wso2/financial-open-banking/issues/95*
------
6. [ ] Have you verified the PR doesn't commit any keys, passwords, …
> [OB3] Fix toolkit build failures due to updated package naming

- open-banking-accelerator/accelerators/ob-apim/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/constant/OpenBankingConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/handler/GatewayClientAuthenticationHandler.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/internal/GatewayDataHolder.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/util/GatewayConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/util/GatewayUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/token/TokenFilter.java
> When a proxy is added to IS APIs through gateway, TLS is terminated at gateway and the Gateway transport certificate is passed to the IS. This causes client authentication failures. This PR adds changes required to pass the client transport certificate to the IS as a header.
**Issue link:** *https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/511*
------
5. [ ] …
> [OB3] Add the option to send transport certificate as a header to IS

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/reporter/OBTimestampPublisher.java
> Currently when a gateway level error is occurred in an API request, 0 is published as response time in the API_LATENCY_RAW_DATA table. This adds the difference between current time and the request time as the response time instead of 0.
**Issue link:** *https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/517*
------ …
> [OB3] Fix publishing 0 as response time on gateway error scenarios

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/pom.xml
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/DataPublisherFactory.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/DataPublisherPool.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/internal/OBAnalyticsDataHolder.java
- pom.xml
> The APIM product has done a tomcat upgrade in this update: 10889, due to this the OB analytics was not working. This PR fixes the issue by utilising a separate library recommended by tomcat to use the functionality of the removed class in this thread: https://www.mail-archive.com/search?l=users@tomcat.apache.org&q=subject:%22Error%22&o=newest&f=1
**Issue link:** *OB internal 847*
**Doc Issue:** **
**Applicable Labels:** *OB 3.0.0, Berlin Toolkit*
------
6. [ ] Have you verified the PR doesn't commit any keys, …
> [OB3] Fixes analytics no class def found issue

- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.application.info.endpoint/src/main/java/com/wso2/open/banking/application/info/endpoint/api/impl/ApplicationInformationApiServiceImpl.java
Currently the consent manager portal shows an error page when there are no consents created and is engaged in an infinite loop trying to fetch data. This PR fixes the issue by returning an empty data json to handle this scenario.
Response body without consents
`{"data":{}}`
Response body with consents 
```
{
"data": {
"<CLIENT_ID>": {
"type": "oauth2",
"Id": "<ID>",
"metadata": {
"software_id": "<SOFTWARE_ID>",
"software_client_name": "WSO2 Open Banking TPP2 (Sandbox)",
"logo_uri": "",
"org_name": "WSO2 (UK) LIMITED",
"client_name": ""
}
}
}
}
```
**Issue link:** https://github.com/wso2-enterprise/wso2-ob-internal/issues/837
------
2. [ ] Ran …
> [OB3][ConsentMgr] Added an empty success response when consent data is not available

- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/model/RegistrationRequest.java
> This PR adds a config to make jwt specific claims (iat, exp, jti) mandatory in DCR requests. To enable the feature, following configs should be added in IS deployment.toml
```
[open_banking.dcr.registration.iat]
required = true
[open_banking.dcr.registration.exp]
required = true
[open_banking.dcr.registration.jti]
required = true
```
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/195*
------
4. [ ] …
>  Provide option to make jwt specific claims in DCR request mandatory

- react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/common/Nav.jsx
- react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/exception/TokenGenerationException.java
- react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/service/APIMService.java
- react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/service/OAuthService.java
- react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/servlet/ApimReqHandlerServlet.java
- react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/util/Constants.java
- react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/util/Utils.java
- react-apps/self-care-portal/src/test/java/com/wso2/openbanking/scp/webapp/service/APIMServiceTest.java
- react-apps/self-care-portal/src/test/java/com/wso2/openbanking/scp/webapp/service/OAuthServiceTest.java
- react-apps/self-care-portal/src/test/java/com/wso2/openbanking/scp/webapp/util/UtilsTest.java
> This PR fixes a bug of `CONFIG` not found to get tenant domain and sync with the support repo consent manager
**Issue link:** N/A
**Applicable Labels:** OB3 Accelerator, CDS Toolkit
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guideline …
> [Consent Manager] Bug fixes and sync with support repo

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/util/PushAuthRequestValidatorUtils.java
The existing PAR audience validation doesn't send an error when the ```aud``` value of the ```par``` request object is equal to the ```par``` endpoint URL. According to the FAPI suite, in this scenario, an error should be thrown. Removing the unnecessary validation to preserve this behavior.
This PR doesn't have the fix introduced with the PR https://github.com/wso2-support/financial-open-banking/pull/3280 reverted because it was not originally merged (this is the closed PR: https://github.com/wso2/financial-services-accelerator/pull/205).
**Related Issue link:** https://github.com/wso2/financial-services-accelerator/issues/208
**Applicable Labels:** OB3, IAM Accelerator
------
2. [x] Ran checkstyle plugin with …
> Remove unnecessary PAR audience validation

- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/config/OpenBankingConfigParser.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/constant/OpenBankingConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/util/PushAuthRequestValidatorUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/PushAuthRequestValidatorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/util/test/jwt/builder/TestJwtBuilder.java
- $subject
**Related Issue link:** 
https://github.com/wso2-enterprise/wso2-ob-internal/issues/921
**Applicable Labels:** OB3
------
2. [ ] Documented test …
> [OB3] Mandating openid scope for PAR requests

- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/config/OpenBankingConfigParser.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/constant/OpenBankingConstants.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/authorize/impl/CIBAConsentPersistStep.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/CIBAWebLinkAuthenticator.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/CIBAWebLinkAuthenticatorConstants.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/CIBAWebLinkAuthenticatorExtensionImpl.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/CIBAWebLinkAuthenticatorExtensionInterface.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/test/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/weblink/CIBAWebLinkAuthenticatorTests.java
This PR improve the adding extension to CIBA authenticator in https://github.com/wso2-support/financial-open-banking/pull/3251
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/128
**Doc Issue:** https://github.com/wso2/docs-open-banking/pull/906
------
8. [ …
> [OB3] [CIBA] Move CIBA customisations to a separate extension class.

- financial-services-accelerator/accelerators/fs-is/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/HTTPClientUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/JWTUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/EventCreationService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/EventPollingService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/EventSubscriptionService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/RealtimeNotificationService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/constants/EventNotificationConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/internal/EventNotificationComponent.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/internal/EventNotificationDataHolder.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/model/RealtimeEventNotification.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/service/DefaultRealtimeEventNotificationRequestGenerator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/service/EventNotificationProducerService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationLoaderService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationRequestGenerator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationSenderService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/util/activator/PeriodicalEventNotificationConsumerJobActivator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/util/job/EventNotificationConsumerJob.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/util/scheduler/PeriodicalEventNotificationConsumerJobScheduler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/util/EventNotificationServiceUtil.java
> This PR adds Realtime Event Notification Implementation
**Issue link:** *https://github.com/wso2-enterprise/solutions-bfsi/issues/20*
------
8. [x] Have you followed secure …
> [Accelerator-4] Adding realtime notification implementation

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/java/com/wso2/openbanking/accelerator/common/test/util/CommonTestUtil.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/claims/OBDefaultOIDCClaimsCallbackHandlerTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/token/util/TestConstants.java
> This PR fixes the build issue due to expired certificates
------ …
> [OB3] Fixed Build Issue due to expired certificates

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/util/TestConstants.java
> Fix uni test issue

- open-banking-accelerator/accelerators/ob-apim/pom.xml
- open-banking-accelerator/accelerators/ob-bi/pom.xml
- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/deployment/server/webapps/api#openbanking#dynamic-client-registration/META-INF/maven/com.wso2/com.wso2.openbanking.accelerator.dcr.endpoint/pom.xml
- open-banking-accelerator/accelerators/ob-is/pom.xml
- open-banking-accelerator/accelerators/pom.xml
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.ciba/pom.xml
- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.demo.backend/src/main/webapp/WEB-INF/web.xml
- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.demosite.endpoint/pom.xml
- open-banking-react-apps/bfsi-apps/consent-approval-ui/pom.xml
- open-banking-react-apps/bfsi-apps/consent-manager-dashboard/pom.xml
- open-banking-react-apps/bfsi-bff/pom.xml
- open-banking-react-apps/pom.xml
- open-banking-sample-toolkit/components/aggregator-gateway/pom.xml
- open-banking-sample-toolkit/components/aggregator-identity/pom.xml
- open-banking-sample-toolkit/pom.xml
- pom.xml
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/222*
------ …
> Fix issue in demo backend and profiles

- README.md
**Applicable Labels:** OB4
------
2. [ ] Documented test scenarios(link available in guides).
3. [ ] Written automation tests (link available in guides).
4. [ ] …
> Add build notes to the README.md file for main branch

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/PushAuthRequestValidator.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/constants/PushAuthRequestConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/util/PushAuthRequestValidatorUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/util/IdentityCommonConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/PushAuthRequestValidatorTest.java
> $subject
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/244*
------
6. [X] Have you verified the PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?
8. [ ] Have you followed secure coding standards in [WSO2 Secure …
> [OB3] Added meaningful error messages for PAR client validations

- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/ConsentCoreService.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/test/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/OBConsentMgtCoreServiceTests.java
> $subject is due to the method `revokeExistingApplicableConsents` is only revoking consents that were created by the admin user
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/253*
------
7. [ ] …
> Fix for recipient count not updating when an active ADR is deleted

- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.authentication.webapp/src/main/webapp/oauth2_authz_displayconsent.jsp
- This PR encodes the unencoded parameters retrieved from the request itself when displaying the consent whether the parameters are generated from within the code or not.
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/294
**Doc Issue:** : N/A
**Applicable Labels:** *OB3 Accelerator*
------ …
> Encode unencoded params in the oauth2_authz_displayconsent.jsp

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/FinancialServicesUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/validate/impl/DefaultConsentValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/validate/DefaultConsentValidatorTest.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentAuthorizeEndpoint.java
> This PR fixes an issue in resolving username from user id
------
8. [x] Have you followed secure coding standards in [WSO2 Secure Engineering …
> [Accelerator-4] Fixed issue resolving username from user id

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/listener/application/OBApplicationManagementListener.java
> This adds support to configure custom token type issuers using the below IAM config.
```
[oauth.extensions.token_types.token_type]
name="<custom name>"
issuer="<custom issuer>"
```
https://github.com/wso2/financial-services-accelerator/issues/296
------
7. [x] Migration scripts written (if applicable).
8. [x] Have you followed secure coding standards in [WSO2 Secure Engineering …
> [OB 3.0.0]Add support to configure custom token type issuers

- open-banking-accelerator/accelerators/ob-apim/carbon-home/repository/conf/open-banking.xml
- open-banking-accelerator/accelerators/ob-apim/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/accelerators/ob-apim/repository/resources/wso2am-4.0.0-deployment.toml
- open-banking-accelerator/accelerators/ob-apim/repository/resources/wso2am-4.1.0-deployment.toml
- open-banking-accelerator/accelerators/ob-apim/repository/resources/wso2am-4.2.0-deployment.toml
- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/conf/open-banking.xml
- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-5.11.0-deployment.toml
- open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-6.0.0-deployment.toml
- open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-6.1.0-deployment.toml
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/DataPublisherFactory.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/constants/DataPublishingConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/internal/OBAnalyticsDataHolder.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/listener/application/OBApplicationManagementListener.java
> This adds support to configure a custom open banking data publisher using the below config.
Example: 
```
[open_banking.data_publishing]
open_banking_data_publisher = "com.wso2.openbanking.accelerator.data.publisher.common.OBThriftDataPublisher"
```
https://github.com/wso2/financial-services-accelerator/issues/315
------
7. [x] Migration scripts written (if applicable). …
>  [OB 3.0.0]Add support to configure custom open banking data publishers

- financial-services-accelerator/accelerators/fs-apim/repository/resources/apis/DynamicClientRegistration/dcr-swagger.yaml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/src/main/java/org/wso2/financial/services/accelerator/gateway/executor/impl/dcr/DCRExecutor.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/src/main/java/org/wso2/financial/services/accelerator/gateway/executor/impl/error/handling/DefaultErrorHandlingExecutor.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/src/main/java/org/wso2/financial/services/accelerator/gateway/util/GatewayConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/src/main/java/org/wso2/financial/services/accelerator/gateway/util/GatewayUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/src/test/java/org/wso2/financial/services/accelerator/gateway/executor/impl/error/handling/DefaultErrorHandlingExecutorTest.java
> This PR fixes issues in error handling in DCR gateway implementation
------
8. [x] Have you followed secure coding standards in [WSO2 Secure …
> [Accelerator 4] Fixed issues in DCR gateway implementation

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/attribute/filter/FSAdditionalAttributeFilter.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/DynamicClientRegistrationValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/IssuerValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/RedirectUriFormatValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/RedirectUriMatchValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/RequestJTIValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/RequiredParamsValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/SSAIssuerValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/SSAJTIValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/TokenEndpointAuthSigningAlgValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/UriHostnameValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/internal/IdentityExtensionsServiceComponent.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/attribute/filter/FSAdditionalAttributeFilterTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/util/TestConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/resources/testng.xml
- pom.xml
> This PR adds DCR Identity Validation Implementation using Additional Attribute FIlter in WSO2 IS
------ …
> [Accelerator 4] DCR Identity Validation Implementation

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/idempotency/IdempotencyValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/ConsentManageHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/ConsentManageValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/builder/ConsentManageBuilder.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/DefaultConsentManageHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/DefaultConsentManageValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/utils/ConsentManageUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/DefaultConsentManageHandlerTest.java
> This PR updates Consent Manage validator and Idempotency validator implementation.
> - Changed consent Manage validator to read its implementation from the config and a method to validate headers.
> - Improved Idemptency validation to include additional spec specific validations.
------
6. [x] Have …
> [Accelerator 4] Updating Consent Manage validator and Idempotency validator implementation

- financial-services-accelerator/accelerators/fs-is/repository/resources/financial-services.yaml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesYamlConfigParser.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/filter/TokenPolicyChainFilter.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/policy/BaseFinancialServicesFilterPolicy.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/policy/ConsentIdResponsePolicy.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/policy/ErrorFormatPolicy.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/policy/FinancialServicesPolicy.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/policy/MTLSEnforcementPolicy.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/policy/TokenDataPublishingPolicy.java
> This PR adds the initial implementation of the yaml config parser and the mechanism to engage financial services policy chain for the /token api calls. Dummy policy implementations are included.
------
2. [ ] Ran Dependency-check plugin and verified …
> [OB5] Add YAML config parser initial state

- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/webapp/WEB-INF/web.xml
> [OB5] Fixed issue in consent manage endpoint

- .github/workflows/maven.yml
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/pom.xml
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/constants/ConsentCoreServiceConstants.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/test/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/OBConsentMgtCoreServiceTests.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/test/java/com/wso2/openbanking/accelerator/consent/mgt/service/util/ConsentMgtServiceTestData.java
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/337
**Doc Issue:**
------
6. [X] Have you verify the PR does't commit any keys, passwords, tokens, usernames, or other secrets?
8. [X] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
2. [ ] …
> [OB3] Refactor updateAccounts method to activate in-active account mappings if needed.

- financial-services-accelerator/accelerators/fs-is/repository/resources/financial-services-sample.yaml
- financial-services-accelerator/accelerators/fs-is/repository/resources/financial-services.yaml
> [OB5] Refactoring the financial-services.yaml

- financial-services-accelerator/accelerators/fs-is/repository/resources/financial-services.yaml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentException.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentManageEndpoint.java
> [OB5] Fix issue in consent manage endpoint

- financial-services-accelerator-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/FSConnectorTest.groovy
- financial-services-accelerator-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/constant/AccountsRequestPayloads.groovy
- financial-services-accelerator-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/constant/CofRequestPayloads.groovy
- financial-services-accelerator-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/constant/ConnectorTestConstants.groovy
- financial-services-accelerator-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/constant/ConsentDataProviders.groovy
- financial-services-accelerator-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/constant/PageObjects.groovy
- financial-services-accelerator-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/constant/PaymentRequestPayloads.groovy
- financial-services-accelerator-test-suite/accelerator-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/test/consent/management/ConsentDeleteTest/ConsentRevokeFlow.groovy
- financial-services-accelerator-test-suite/accelerator-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/test/consent/management/ConsentInitiationTest/ConsentInitiationTest.groovy
- financial-services-accelerator-test-suite/accelerator-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/test/consent/management/ConsentOperationsFlowTests/ConsentManageEndpointValidationTest.groovy
- financial-services-accelerator-test-suite/accelerator-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/test/consent/management/ConsentValidateTest/AccountConsentValidationFlow.groovy
- financial-services-accelerator-test-suite/accelerator-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/test/consent/management/ConsentValidateTest/COFConsentValidationFlow.groovy
- financial-services-accelerator-test-suite/accelerator-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/test/consent/management/ConsentValidateTest/PaymentConsentValidationFlow.groovy
- financial-services-accelerator-test-suite/accelerator-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/test/consent/management/EndToEndTest/EndToEndConsentManagementFlowTest.groovy
- financial-services-accelerator-test-suite/accelerator-tests/consent-management/src/test/resources/testng.xml
> [OB5] Adding consent validate API tests

- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentManageEndpoint.java
> [OB5] Fixed build issue in Consent Manage Endpoint

- .github/workflows/maven.yml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/webapp/WEB-INF/web.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.event.notifications.endpoint/src/main/webapp/WEB-INF/web.xml
> [Accelerator 4 ] Remove spring dependencies

- README.md
- financial-services-accelerator/accelerators/fs-apim/README.md
- financial-services-accelerator/accelerators/fs-apim/pom.xml
- financial-services-accelerator/accelerators/fs-is/README.md
- financial-services-accelerator/accelerators/fs-is/pom.xml
- financial-services-accelerator/accelerators/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.demo.backend/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.event.notifications.endpoint/pom.xml
- financial-services-accelerator/pom.xml
- integration-test-framework/bfsi-test-framework/pom.xml
- integration-test-framework/open-banking-test-framework/pom.xml
- integration-test-framework/pom.xml
- pom.xml
- react-apps/pom.xml
> Update versions of all files from 4.0.0 to 5.0.0
------ …
> [OB5] Pom version change for 5.0.0-M1-SNAPSHOT

- react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/service/APIMService.java
- react-apps/self-care-portal/src/test/java/com/wso2/openbanking/scp/webapp/service/APIMServiceTest.java
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/363
**Doc Issue:**
------
6. [X] Have you verify the PR does't commit any keys, passwords, tokens, usernames, or other secrets?
8. [X] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
2. [ ] …
> [OB3] [Consentmgr] Update host header when forwarding to apim

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/extension/model/AllowedOperations.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/extension/model/ExternalServiceRequest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/DefaultConsentManageValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/validate/builder/ConsentValidateBuilder.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/validate/impl/ConsentValidatorServiceExtension.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/validate/model/ConsentValidateRequest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/util/DataProviders.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/validate/ConsentValidatorServiceExtensionTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/resources/testng.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/validators/RequestJTIValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/util/TestConstants.java
> This PR adds the improvement in consent validation to support external service invoking
------
8. [x] Have you followed secure coding standards …
> [OB4] Improvement in consent validation to support external service invoking

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/extension/model/ServiceExtensionTypeEnum.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/models/ConsentResource.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/ExternalAPIConsentManageHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentGenerateRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentGenerateResponseDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRetrieveRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRetrieveResponseDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRevokeRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRevokeResponseDTO.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentManageEndpoint.java
> This PR adds consent manage handler that gives capability to handle manage requests using an external service.
------
8. [ ] Have you followed secure coding standards in …
> [OB4-M2] Add consent manage external service handler

- open-banking-accelerator/accelerators/ob-apim/repository/resources/apis/ConfirmationOfFunds/cof-dynamic-endpoint-insequence.xml
- open-banking-accelerator/accelerators/ob-apim/repository/resources/apis/Payments/payments-dynamic-endpoint-insequence.xml
> [OB3] Adding cof and payment insequences

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/conf/financial-services.xml
- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/extension/model/OperationEnum.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/request/validator/DefaultFSRequestObjectValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/request/validator/FSRequestObjectValidationExtension.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/request/validator/FSRequestObjectValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/response/handler/impl/FSDefaultResponseTypeHandlerImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSAuthorizationCodeGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSClientCredentialsGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSDefaultGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSPasswordGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSRefreshGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/internal/IdentityExtensionsDataHolder.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/request/validator/DefaultFSRequestObjectValidatorTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/request/validator/RequestObjectValidatorTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/attribute/filter/FSAdditionalAttributeFilterTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/resources/testng.xml
> [OB4] Request object validation and Grant handler extension

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIPreConsentGenerateRequestDTO.java
> Fix invalid variable name in ExternalAPIPreConsentGenerateRequestDTO
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure …
> [OB4-M3] Fix invalid model variable

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentRetrievalStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ExternalAPIUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/ExternalAPIConsentManageHandler.java
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
1. [ ] …
> [OB4-M3] Add error handling logic to consent manage and pre authorization

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/ExternalAPIConsentManageHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRevokeRequestDTO.java
> [OB4 - M3] Fix ExternalAPIConsentRevokeRequestDTO

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIPostConsentGenerateRequestDTO.java
> [OB4-M3] Fix issue in consent manage post consent generation

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/conf/financial-services.xml
- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/JWTUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/claims/FSClaimProvider.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/interceptor/FSDefaultIntrospectionDataProvider.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/interceptor/FSIntrospectionDataProvider.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/internal/IdentityExtensionsDataHolder.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/internal/IdentityExtensionsServiceComponent.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonUtils.java
> [OB4] Fixed consent ID issue and added introspect data provider

- financial-services-accelerator/accelerators/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonUtils.java
> [OB4-M3] Updated scope request param issue

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/ExternalAPIConsentManageHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRetrieveRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRevokeResponseDTO.java
> [OB4-M3] Add proper json conversion to ExternalAPIConsentRetrieveRequestDTO

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/request/validator/FSRequestObjectValidationExtension.java
> [OB4-M3] Removed operation filed getting added to the request

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/model/ExternalAPIPreConsentAuthorizeRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/ExternalAPIConsentManageHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRetrieveRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRevokeRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRevokeResponseDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIPostConsentGenerateRequestDTO.java
> [OB4-M3] Update dto models

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/models/ConsentResource.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRetrieveRequestDTO.java
> [OB4-M3] Fix issue in ExternalAPIConsentRetrieveRequestDTO json conversin logic

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/ExternalAPIConsentManageHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRevokeRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIPostConsentGenerateRequestDTO.java
> [OB4-M3] Add proper json conversion to missed DTOs

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentRetrievalStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/model/ExternalAPIPreConsentAuthorizeRequestDTO.java
> [OB4-M3] Update ExternalAPIPreConsentAuthorizeRequestDTO model

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/ExternalAPIConsentManageHandler.java
> [OB4-M3] Get consent status from external response

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
This element is not following common naming convension used by OB team.Thus corrected it and updated .j2 to support both old and new names
------
6. [x] Have you verified the PR doesn't commit any keys, passwords, tokens, usernames, or other …
> Added OpenAPI file for accelerator extensions & fixed toml config element

- financial-services-accelerator/accelerators/fs-apim/pom.xml
- financial-services-accelerator/accelerators/fs-is/pom.xml
- financial-services-accelerator/accelerators/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.demo.backend/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.event.notifications.endpoint/pom.xml
- financial-services-accelerator/pom.xml
- fs-integration-test-suite/accelerator-test-framework/pom.xml
- fs-integration-test-suite/accelerator-tests/consent-management/pom.xml
- fs-integration-test-suite/accelerator-tests/dcr/pom.xml
- fs-integration-test-suite/accelerator-tests/gateway-integration/pom.xml
- fs-integration-test-suite/accelerator-tests/pom.xml
- fs-integration-test-suite/accelerator-tests/token/pom.xml
- fs-integration-test-suite/pom.xml
- integration-test-framework/bfsi-test-framework/pom.xml
- integration-test-framework/open-banking-test-framework/pom.xml
- integration-test-framework/pom.xml
- pom.xml
> Version bumped to 4.0.0-M3

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ExternalAPIUtil.java
> This PR adds proper error handling logic to the consent manage external service handler. The 'error-code' and 'data' from the external response are used to respond to the consent-manage API caller.
------
6. [ ] Have you verified the PR doesn't commit any keys, passwords, tokens, usernames, or other …
> [OB4-M4] Improve consent manage error handling

- fs-integration-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/constant/AccountsRequestPayloads.groovy
- fs-integration-test-suite/accelerator-tests/gateway-tests/accounts/pom.xml
- fs-integration-test-suite/accelerator-tests/gateway-tests/dcr/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/consent-management/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/is/test/consent/management/ConsentRetrieval/ConsentRetrievalFlow.groovy
- fs-integration-test-suite/accelerator-tests/is-tests/pom.xml
- fs-integration-test-suite/accelerator-tests/pom.xml
- fs-integration-test-suite/bfsi-test-framework/src/main/groovy/org/wso2/bfsi/test/framework/request_builder/SignedObject.groovy
- pom.xml
> [OB4] Fix issue in accelerator tests

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/ServiceExtensionUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/java/org/wso2/financial/services/accelerator/common/test/util/ServiceExtensionUtilsTest.java
> [OB4] Changed to service extension invoker to https client

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/ConsentCoreDAO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/impl/ConsentCoreDAOImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/models/ConsentResource.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/queries/ConsentMgtCommonDBQueries.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/dao/impl/ConsentCoreDAOTests.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/ConsentCoreService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/util/ConsentCoreServiceUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/service/impl/ConsentMgtCoreServiceTests.java
> This PR adds 2 new methods to consent core service to insert and update a complete DetailedConsentResource. Related DAO level changes are also included.
------
7. [ ] Migration scripts written …
> [OB4-M4] Add consent core service changes

- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/extension/model/ServiceExtensionTypeEnum.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/ServiceExtensionUtils.java
> [OB4] Modified allowed extensions configuration

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigParser.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
> [OB4] Added configs related to consent id extraction in auth flow

- financial-services-accelerator/accelerators/fs-apim/carbon-home/repository/conf/financial-services.xml
- financial-services-accelerator/accelerators/fs-apim/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/conf/financial-services.xml
- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigParser.java
> [OB4] Fixing issue in encrypted passwords with the cipher tool are not being decrypted

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ExternalAPIUtil.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/error/ConsentThrowableMapper.java
> [OB4] Fixed error mapping issue

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentPersistStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentRetrievalStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authservlet/impl/FSDefaultAuthServletImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authservlet/utils/Utils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ExternalAPIUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authservlet/FSDefaultAuthServletImplTest.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/webapp/fs_default.jsp
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/webapp/js/auth-functions.js
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentAuthorizeEndpoint.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/utils/ConsentConstants.java
> This PR contains changes to support non-initiated consents (eg: CDS Spec).
------
8. [ ] Have you followed secure coding standards in [WSO2 …
> [OB4 - M4] Add support for non initiated consents

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/DataPublisherFactory.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/internal/OBAnalyticsDataHolder.java
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/454
**Doc Issue:**
------
6. [X] Have you verify the PR does't commit any keys, passwords, tokens, usernames, or other secrets?
8. [X] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
2. [ ] …
>  [OB3] Fix data publishing connection refused error log even when data publishing disabled.

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/exception/FinancialServicesDCRException.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/attribute/filter/FSAdditionalAttributeFilter.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/extension/FSAbstractDCRExtension.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/extension/FSDefaultDCRExtension.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/DynamicClientRegistrationValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/IssuerValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/RedirectUriFormatValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/RedirectUriMatchValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/RequestJTIValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/RequiredParamsValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/SSAIssuerValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/SSAJTIValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/TokenEndpointAuthSigningAlgValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/UriHostnameValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonConstants.java
> [OB4] Fixing issues in DCR flow

- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/ErrorConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/request/validator/FSRequestObjectValidationExtension.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/response/handler/FSCodeResponseTypeHandlerExtension.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/response/handler/FSHybridResponseTypeHandlerExtension.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/claims/FSClaimProvider.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSAuthorizationCodeGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSClientCredentialsGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSPasswordGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/grant/type/handlers/FSRefreshGrantHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/interceptor/FSIntrospectionDataProvider.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/claims/FSClaimProviderTest.java
> [OB4] Getting consent id for extensions based on consent type

- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/application/listener/FSApplicationManagementListener.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/attribute/filter/FSAdditionalAttributeFilter.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/attribute/filter/FSAdditionalAttributeFilterTest.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/error/ConsentThrowableMapper.java
> This PR fixes the following issues.
> - https://github.com/wso2/financial-services-accelerator/issues/477
> - https://github.com/wso2/financial-services-accelerator/issues/478
> - https://github.com/wso2/financial-services-accelerator/issues/482
> - Setting DCR scopes for the application
------
6. [ …
> [Accelerator 4] Fix issues in DCR flow

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/ConsentCoreDAO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/constants/ConsentMgtDAOConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/impl/ConsentCoreDAOImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/models/DetailedConsentResource.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/queries/ConsentMgtCommonDBQueries.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/DefaultConsentRetrievalStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentPersistStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentRetrievalStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/model/AmendedResources.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/model/ExternalAPIPreConsentAuthorizeRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/model/ExternalAPIPreConsentPersistRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/model/ExternalAPIPreConsentPersistResponseDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/util/ConsentAuthorizeUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ExternalAPIUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/ConsentCoreService.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/constants/ConsentCoreServiceConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
> This PR adds consent amandment / re-authorization capability that can be supported using API extension. To support that, this also includes the changes to send the detailed consent resource to the extension.
------
7. [ ] …
> [Accelerator 4] Add consent amendment feature using extension

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigParser.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/ServiceExtensionUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/java/org/wso2/financial/services/accelerator/common/test/util/ServiceExtensionUtilsTest.java
> [OB4] Implemented retry timeout for service extension endpoint invocations

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/model/ExternalAPIConsentResourceResponseDTO.java
> [OB4 - M4] Remove non updatable parameters from ExternalAPIConsentResourceResponseDTO

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/ServiceExtensionUtils.java
> [OB4] Handling only retryable exceptions

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/ServiceExtensionUtils.java
> [OB4] Refactored code

- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
> Updated toml config with all the extensions

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/attribute/filter/FSAdditionalAttributeFilter.java
> Fix issue in accelerator DCR

- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/constant/OpenBankingConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/common/annotations/validationgroups/MandatorySsaChecks.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/common/annotations/validationorder/ValidationOrder.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/model/RegistrationRequest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/RequiredSsaParamsValidator.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/annotation/ValidateRequiredSsaParams.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/dcr/DCRExtendedValidatorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/dcr/DCRValidationTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/dcr/util/RegistrationTestConstants.java
With this we are introducing a new config to the IS deployment.toml as below,
```
[open_banking.dcr.registration.software_statement]
mandatory_parameters = ["iss", "iat", "exp", "jti", "org_id", "org_name", "client_description", "client_uri",
"redirect_uris_test", "logo_uri", "jwks_uri", "revocation_uri", "recipient_base_uri", "software_id", "software_roles",
"scope"]
```
With the above config, we are checking whether the SSA body presents the above mentioned mandatory parameters. This validation expected to happen after the mandatary parameter validation in the DCR request body.
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/492
**Doc Issue:**
------
1. [X] Built complete solution with pull …
> [OB3] Add DCR SSA Mandatory parameter validation.

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentPersistStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionConstants.java
> [OB4 - M4] Add userId to external API pre persistence request

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentException.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionConstants.java
> [Accelerator 4] Fix issue in accelerator consent exception throwing in auth flow

- financial-services-accelerator/accelerators/fs-apim/pom.xml
- financial-services-accelerator/accelerators/fs-is/pom.xml
- financial-services-accelerator/accelerators/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.demo.backend/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.event.notifications.endpoint/pom.xml
- financial-services-accelerator/pom.xml
- fs-integration-test-suite/accelerator-test-framework/pom.xml
- fs-integration-test-suite/accelerator-tests/gateway-tests/accounts/pom.xml
- fs-integration-test-suite/accelerator-tests/gateway-tests/dcr/pom.xml
- fs-integration-test-suite/accelerator-tests/gateway-tests/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/consent-management/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/dcr/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/event-notification/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/token/pom.xml
- fs-integration-test-suite/accelerator-tests/pom.xml
- fs-integration-test-suite/bfsi-test-framework/pom.xml
- fs-integration-test-suite/pom.xml
- pom.xml
> Updated main to 4.0.0-SNAPSHOT

- financial-services-accelerator/accelerators/fs-apim/pom.xml
- financial-services-accelerator/accelerators/fs-is/pom.xml
- financial-services-accelerator/accelerators/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.gateway/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.demo.backend/pom.xml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.event.notifications.endpoint/pom.xml
- financial-services-accelerator/pom.xml
- fs-integration-test-suite/accelerator-test-framework/pom.xml
- fs-integration-test-suite/accelerator-tests/gateway-tests/accounts/pom.xml
- fs-integration-test-suite/accelerator-tests/gateway-tests/dcr/pom.xml
- fs-integration-test-suite/accelerator-tests/gateway-tests/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/consent-management/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/dcr/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/event-notification/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/pom.xml
- fs-integration-test-suite/accelerator-tests/is-tests/token/pom.xml
- fs-integration-test-suite/accelerator-tests/pom.xml
- fs-integration-test-suite/bfsi-test-framework/pom.xml
- fs-integration-test-suite/pom.xml
- pom.xml
> [Accelerator 4] Version bump to 4.0.0-alpha-SNAPSHOT

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigParser.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/DefaultConsentManageHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ConsentManageData.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRetrieveRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIConsentRevokeRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIPreConsentGenerateRequestDTO.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentManageEndpoint.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/utils/ConsentUtils.java
> This PR adds changes required to allow whitelisted headers in the consent manage extension api calls (POST, GET, DELETE),
------
8. [ ] Have you …
> [OB4] Add header whitelisting capability to the consent manage extension

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/ServiceExtensionUtils.java
> This PR improves the formatting and adds request url to the debug logs of the api extension service.
------
8. [ ] Have you followed secure …
> [OB4] Improve service extension call debug logs

- financial-services-accelerator/accelerators/fs-apim/README.md
- financial-services-accelerator/accelerators/fs-apim/bin/configure.sh
- financial-services-accelerator/accelerators/fs-apim/bin/merge.sh
- financial-services-accelerator/accelerators/fs-is/README.md
- financial-services-accelerator/accelerators/fs-is/bin/configure.sh
- financial-services-accelerator/accelerators/fs-is/bin/merge.sh
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/internal/FinancialServicesCommonDataHolder.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/internal/FinancialServicesCommonServiceComponent.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/HTTPClientUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/ServiceExtensionUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/resources/findbugs-exclude.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/java/org/wso2/financial/services/accelerator/common/test/util/ServiceExtensionUtilsTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationSenderService.java
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/525*
------ …
> [Accelerator-4] Improving HTTP client creation and shell scripts

- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
> [Accelerator4.0] Updated the accelerator extensions swagger

- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
1. [ ] …
> [OB4] Update API extension swagger file retrieval request body

- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/extension/model/ServiceExtensionTypeEnum.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/impl/DefaultConsentAdminHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/model/ExternalAPIAdminConsentRevokeRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/model/ExternalAPIAdminConsentSearchRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/model/ExternalAPIAdminConsentSearchResponseDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/model/SearchTypeEnum.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/utils/ExternalAPIConsentAdminUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/DefaultConsentAdminHandlerTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/util/TestUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/resources/testng.xml
> Added fixes for consent revoke,search api extension points

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/internal/FinancialServicesCommonDataHolder.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/internal/FinancialServicesCommonServiceComponent.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/internal/ConsentMgtServiceComponent.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/internal/EventNotificationComponent.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/internal/IdentityExtensionsDataHolder.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentValidationEndpoint.java
> [Accelerator 4] Fix issue in throwing exceptions from service components

- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/450, https://github.com/wso2/financial-services-accelerator/issues/551*
------
7. [ ] …
> [Accelerator] Fix issues identified in Alpha testing

- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
> This PR updates the extensions API swagger to fix consent reauthorization scenario issues.
------
8. [ ] Have you followed secure coding …
> [OB4] Update extensions api swagger

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/NonRegulatoryConsentStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authservlet/impl/ISDefaultAuthServletImpl.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/java/org/wso2/financial/services/accelerator/authentication/endpoint/FSConsentServlet.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/java/org/wso2/financial/services/accelerator/authentication/endpoint/util/Constants.java
> [Accelerator 4] Fix issue in non initiated flow with default consent type

- fs-integration-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/FSConnectorTest.groovy
- fs-integration-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/constant/RequestPayloads.groovy
- fs-integration-test-suite/accelerator-test-framework/src/main/groovy/org/wso2/financial/services/accelerator/test/framework/utility/TestUtil.groovy
- fs-integration-test-suite/accelerator-tests/is-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/is/test/consent/management/PaymentsApiTests/InitiationRequestHeaderValidationTests.groovy
- fs-integration-test-suite/accelerator-tests/is-tests/consent-management/src/test/resources/testng.xml
> [Accelerator 4] [TestSuite] Adding payment header validation tests including idempotency tests

- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentValidationEndpoint.java
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/553, https://github.com/wso2/financial-services-accelerator/issues/590*
------
7. [ ] …
> [Accelerator 4] Fix issues in consent flows

- financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigParser.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/FinancialServicesUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/java/org/wso2/financial/services/accelerator/common/test/FSConfigParserTests.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/java/org/wso2/financial/services/accelerator/common/test/util/FinancialServicesUtilsTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/resources/repository/conf/financial-services.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/impl/DefaultConsentAdminHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/util/ConsentAuthorizeUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/DefaultConsentRetrievalStepTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/idempotency/IdempotencyValidatorTests.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/util/TestConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/validate/DefaultConsentValidatorTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/claims/FSClaimProvider.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/claims/FSDefaultOIDCClaimsCallbackHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/application/listener/FSApplicationManagementListener.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/attribute/filter/FSAdditionalAttributeFilter.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/dcr/validators/RequiredParamsValidator.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/interceptor/FSIntrospectionDataProvider.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityServiceExtensionUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/claims/FSClaimProviderTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/claims/FSDefaultOIDCClaimsCallbackHandlerTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/attribute/filter/FSAdditionalAttributeFilterTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/test/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonUtilsTest.java
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/572, https://github.com/wso2/financial-services-accelerator/issues/589*
------
7. [ ] …
> [Accelerator 4] Bug fixes

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/utils/ExternalAPIConsentAdminUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentPersistStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentRetrievalStep.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/utils/ExternalAPIConsentManageUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/client/registration/application/listener/FSApplicationManagementListener.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentAuthorizeEndpoint.java
> This PR adds changes to create Gson instances at object initialization itself instead of per call to improve performance.
------
8. [ ] Have you followed secure coding …
> [OB4][Perf] Make gson a class variable

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/model/ExternalAPIPostFileUploadRequestDTO.java
> Fixed filePayment request dto variable name

- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.0.0.yaml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.1.0-deployment.toml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/impl/DefaultConsentAdminHandler.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/model/ExternalAPIAdminConsentSearchRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/model/ExternalAPIAdminConsentSearchResponseDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/admin/utils/ExternalAPIConsentAdminUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
- financial-services-accelerator/react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/api/consent-api.js
- financial-services-accelerator/react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/context/SearchObjectContext.js
- financial-services-accelerator/react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/landing_page/Body.jsx
> This PR fixes the following issues in Consent Manager Portal
> - Consent Search is not working when external extension is enabled
> - Issue in external service serach request and response 
> - Consent revocation is not working for PSU
> - User Id filter option is not working properly in Search Advanced 
> - UI issue in Advanced Search
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/617, https://github.com/wso2/financial-services-accelerator/issues/618, https://github.com/wso2/financial-services-accelerator/issues/576*
------
1. [ ] Build complete solution with pull …
> [Accelerator 4] Fix issues in consent manager

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/624*
------ …
> [Accelerator 4] Fix issue in consent revocation

- financial-services-accelerator/react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/specConfigs/specConfigurations.js
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/632*
------ …
> [Accelerator 4] Fix issue in status values in consent manager portal

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/dao/EventSubscriptionDAOImpl.java
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/636*
------ …
> [Accelerator 4] Fix issue in subscription retrieval db execution for mssql

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/main/java/org/wso2/financial/services/accelerator/event/notifications/service/dao/PostgreSqlEventNotificationDAOImpl.java
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/630
------ …
> Fixed #630

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigParser.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/extension/model/ServiceExtensionTypeEnum.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/CertificateUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/FinancialServicesUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/java/org/wso2/financial/services/accelerator/common/test/util/CertificateUtilsTest.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/java/org/wso2/financial/services/accelerator/common/test/util/testutils/CommonTestUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/resources/testng.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/pom.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/FSKeyManagerConfiguration.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/FSKeyManagerExtensionImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/FSKeyManagerExtensionInterface.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/FSKeyManagerImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/dto/ExternalAPIApplicationCreationRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/dto/ExternalAPIApplicationCreationResponseDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/dto/ExternalAPIApplicationUpdateRequestDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/dto/ExternalAPIApplicationUpdateResponseDTO.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/internal/KeyManagerDataHolder.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/internal/KeyManagerServiceComponent.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/utils/FSKeyManagerConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/utils/FSKeyManagerUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/utils/IdentityServerUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/resources/findbugs-exclude.xml
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/resources/findbugs-include.xml
- financial-services-accelerator/pom.xml
- pom.xml
> [Accelerator 4] Adding Key Manager Implementation

- financial-services-accelerator/accelerators/fs-apim/repository/resources/insequence/dynamicEndpointInsequence.j2
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/686*
------ …
> [Accelerator 4] Fixed schema validation issue

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/auth/extensions/request/validator/annotations/NbfExpClaimsValidator.java
> $subject
- with `nbf = current time + ~80 s` , this is allowed from nimbus library when signature validations, hence return `Request+object+is+not+valid+yet` from the OB validations.
- However with `nbf = current time + 100 s` , this is not allowed from nimbus library when signature validations, hence return `Error+occurred+while+validating+request+object+signature+using+jwks+endpoint:request+object+is+not+valid+yet.` from the IS validations before it hits the OB validations.
With this PR, we sync the error message from OB to be equal with IS.
**Issue link:** 
https://github.com/wso2/financial-services-accelerator/issues/691
**Applicable Labels:** UK Toolkit
------
1. [X] Built …
> [OB3] Sync nbf validation error msg to match with product IS

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/FSKeyManagerImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/utils/FSKeyManagerConstants.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/utils/FSKeyManagerUtil.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.keymanager/src/main/java/org/wso2/financial/services/accelerator/keymanager/utils/IdentityServerUtils.java
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/677*
------ …
> [Accelerator 4] Fixed issue key generation for non-regulatory applications

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/model/RegistrationResponse.java
> Currently we are sending a string value for the client_id_issued_at field in DCR response. According to RFC7591 (https://datatracker.ietf.org/doc/html/rfc7591) this should be an integer. This PR changes the client_id_issued_at value type to integer in DCR POST, GET, PUT requests.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/697*
------
5. [ ] …
> [OB3] Change the type of DCR response client_id_issued_at field to integer

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/java/com/wso2/openbanking/accelerator/common/test/util/CommonTestUtil.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/claims/OBDefaultOIDCClaimsCallbackHandlerTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/token/util/TestConstants.java
This PR address the build issue due to the expired certificates. from [1]
[1] https://github.com/wso2-enterprise/bfsi-test-resources/pull/73
**Issue link:** 
------
2. [ ] Ran Dependency-check plugin and verified report for new dependencies added.
2. [ ] Ran Dependency-check …
> [OB3] Fix unit test failure due to expired certificates.

- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.0.0.yaml
- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.0.2.yaml
> This PR introduces the data models expected by the new cross-compatible implementation of the consent authorize page
------
8. [x] Have you …
> Update openapi definitions to support new consent page

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/dcr/DCRExecutor.java
> Although SSA mandatory parameter validation is present in the IS Accelerator DCR Request Validator, the jwks_uri parameter is used in the DCRExecutor, which is executed before IS Accelerator validation. This causes a null pointer if the jwks_uri is not present ins the SSA. This PR is to validate the presence of jwks_uri parameter, and return an error form the DCRExecutor if it is not present in the SSA.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/751*
------
2. [x] Ran checkstyle plugin with pull request in …
> [OB3] Make jwks_uri mandatory in SSA

- pom.xml
> Upgrade apache-commons-bean-utils version from 1.9.3 to 1.11.0
Upgrade jackson-core version from 2.12.0 to 2.17.2
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/759*
------
2. [ ] Ran Dependency-check plugin and verified report for new …
> [OB3] Upgrade jackson and beanutil versions

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/impl/consent/ConsentEnforcementExecutor.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/util/GatewayUtils.java
> This pr fixes improper handling of Http clients
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/765
------
8. [x] Have you followed secure …
> Fix improper handling of Http clients

- .github/workflows/maven.yml
> Updating the workflow to read git secrets

- .github/workflows/maven.yml
- financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.0.2.yaml
> Updating accelerator extension swagger

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/util/ConsentAuthorizeUtil.java
> Fix issue in account id returning null in default flow

- financial-services-accelerator/react-apps/self-care-portal/src/main/java/org/wso2/financial/services/accelerator/scp/webapp/servlet/OAuthCallbackServlet.java
> Fix issue in throwing null pointer in consent manager logout

- open-banking-accelerator/accelerators/ob-apim/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/config/OpenBankingConfigParser.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/constant/OpenBankingConstants.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/HTTPClientUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/SPQueryExecutorUtil.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/java/com/wso2/openbanking/accelerator/common/test/OBConfigParserTests.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/resources/open-banking.xml
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/dcr/DCRExecutor.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/impl/consent/ConsentEnforcementExecutor.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/revocation/CRLValidator.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/revocation/OCSPValidator.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/internal/GatewayDataHolder.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/util/GatewayUtils.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/notification/provider/SMSNotificationProvider.java
- open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/main/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationSenderService.java
- open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/test/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationSenderServiceTests.java
> This pr,
- adds support to configure HTTP connection TTL.
- refactor HTTP client usages to ensure connection release after usage.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/765*
------
1. [x] Ran FindSecurityBugs plugin and verified report.
2. [ ] Ran Dependency-check plugin and verified report …
> Improve http client connection usage

- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/HTTPClientUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/SPQueryExecutorUtil.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/java/com/wso2/openbanking/accelerator/common/test/util/SPQueryExecutorUtilTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/dcr/DCRExecutor.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/impl/consent/ConsentEnforcementExecutor.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/revocation/CRLValidator.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/revocation/OCSPValidator.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/internal/GatewayDataHolder.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/util/GatewayUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/test/java/com/wso2/openbanking/accelerator/gateway/executor/revocation/CRLValidatorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/test/java/com/wso2/openbanking/accelerator/gateway/executor/revocation/OCSPValidatorTest.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/authenticator/OBIdentifierAuthenticator.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/util/HTTPClientUtils.java
- open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/authenticator/OBIdentifierAuthenticatorTest.java
- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/notification/provider/SMSNotificationProvider.java
- open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/main/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationSenderService.java
- open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/test/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationSenderServiceTests.java
- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.consent.endpoint/src/main/java/com/wso2/openbanking/accelerator/consent/endpoint/util/ConsentUtils.java
- react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/util/Utils.java
- react-apps/self-care-portal/src/test/java/com/wso2/openbanking/scp/webapp/util/UtilsTest.java
> This pr,
- adds a new method to get http client to keep backward compatibility
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/765*
------
1. [x] Ran FindSecurityBugs plugin and verified report.
2. [ ] Ran Dependency-check plugin and verified report for new dependencies added.
2. [ ] Ran …
> Refactor HTTP Client usage

- financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.2.0-deployment.toml
> Adding is-7.2.0 toml

- fs-integration-test-suite/accelerator-tests/is-tests/token/src/test/groovy/grant_type_validation/RefreshTokenGrantAccessToken.groovy
> Fix issue in refresh token test

- financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/JWTUtils.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/impl/ConsentCoreDAOImpl.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/dao/queries/ConsentMgtCommonDBQueries.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/job/ExpiredConsentStatusUpdateJob.java
- financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/job/ExpiredConsentStatusUpdateJobTests.java
- financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.consent.mgt.endpoint/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/endpoint/api/ConsentValidationEndpoint.java
> This PR fixes below issues.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/738, https://github.com/wso2/financial-services-accelerator/issues/804*
------
7. [ ] Migration scripts written (if …
> [OB4] Fix Accelerator issues in consent expiration and consent validation

- pom.xml
> This pr is to avoid build failure in public nexus release
------ …
> Remove integration-test-framework build from root pom

- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.application.info.endpoint/src/main/webapp/WEB-INF/web.xml
- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.consent.endpoint/src/main/webapp/WEB-INF/web.xml
- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.dcr.endpoint/src/main/webapp/WEB-INF/web.xml
- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.event.notifications.endpoint/src/main/webapp/WEB-INF/web.xml
- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.push.authorization.endpoint/src/main/webapp/WEB-INF/web.xml
> Remove spring dependencies from webapps
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/802*
------ …
> Remove spring dependencies

- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.application.info.endpoint/src/main/webapp/WEB-INF/web.xml
- open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.event.notifications.endpoint/src/main/webapp/WEB-INF/web.xml
> Remove spring dependencies from webapps
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/802*
------ …
> [OB3][IS]Remove spring dependencies

- open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
> This pr change log level at [1] to debug to remove misleading error logs printed when querying consent attributes.
**Issue link:** *[required](https://github.com/wso2/financial-services-accelerator/issues/811)*
------
7. [ …
> Change data retrieval error log to debug

- financial-services-accelerator/accelerators/fs-apim/README.md
- financial-services-accelerator/accelerators/fs-apim/bin/configure.ps1
- financial-services-accelerator/accelerators/fs-apim/bin/configure.sh
- financial-services-accelerator/accelerators/fs-apim/bin/merge.ps1
- financial-services-accelerator/accelerators/fs-apim/bin/merge.sh
- financial-services-accelerator/accelerators/fs-apim/pom.xml
- financial-services-accelerator/accelerators/fs-apim/repository/conf/configure.properties
- financial-services-accelerator/accelerators/fs-apim/repository/resources/wso2am-4.4.0-deployment.toml
- financial-services-accelerator/accelerators/fs-apim/repository/resources/wso2am-4.5.0-deployment.toml
- financial-services-accelerator/accelerators/pom.xml
> This PR adds the APIM Accelerator artifacts copying, config files and zip creation logics
------
8. [ ] Have you followed secure coding standards …
> Adding APIM Accelerator zip generation logic

- fs-integration-test-suite/accelerator-tests/gateway-tests/accounts/src/test/groovy/org/wso2/financial/services/accelerator/gateway/test/accounts/Consent_Initiation_Tests/AccountsInitiationRequestHeaderValidationTests.groovy
- fs-integration-test-suite/accelerator-tests/is-tests/consent-management/src/test/groovy/org/wso2/financial/services/accelerator/is/test/consent/management/EndToEndTest/EndToEndConsentManagementFlowTest.groovy
> Fix test failures
