open-banking-accelerator/accelerators/ob-apim/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
open-banking-accelerator/accelerators/ob-apim/repository/resources/wso2am-4.0.0-deployment.toml
open-banking-accelerator/accelerators/ob-apim/repository/resources/wso2am-4.1.0-deployment.toml
open-banking-accelerator/accelerators/ob-apim/repository/resources/wso2am-4.2.0-deployment.toml
open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-5.11.0-deployment.toml
open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-6.0.0-deployment.toml
open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-6.1.0-deployment.toml
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/AnalyticsLogsUtils.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/pom.xml
open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/constants/DataPublishingConstants.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/main/java/com/wso2/openbanking/accelerator/data/publisher/common/util/OBDataPublisherUtil.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.data.publisher/com.wso2.openbanking.accelerator.data.publisher.common/src/test/java/com/wso2/openbanking/accelerator/data/publisher/common/OBAnalyticsEventQueueTest.java

> This PR will introduce a method to publish analytics logs to an OB analytics log file so that those logs could be processed using Logstash when implementing ELK support for the OB Accelerator.
**Issue link:** *[wso2/financial-open-banking#11](https://github.com/wso2/financial-open-banking/issues/11)*
**Applicable Labels:** *ob-3.0.0, OB Accelerator*
------
6. [X] Have you verify the PR does't commit any …

[OB3] Publishing OB Analytics logs required to implement ELK Support for the OB Accelerator

---

open-banking-accelerator/accelerators/ob-apim/pom.xml
open-banking-accelerator/accelerators/ob-is/pom.xml

**Issue link:** https://github.com/wso2/financial-open-banking/issues/42
**Doc Issue:** 
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)? 
2. …

[OB3] Remove default mysql connecter jar

---

open-banking-accelerator/internal-apis/internal-webapps/com.wso2.openbanking.accelerator.dcr.endpoint/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/endpoint/impl/util/RegistrationUtils.java

This PR fix below issue.
**Issue link:** https://github.com/wso2-enterprise/ob-compliance-toolkit-uk/issues/405
**Doc Issue:** 
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidel …

[OB3] Fix DCR failure when SSA contain 'null' for optional values

---

open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyConstants.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyValidationUtils.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyValidator.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/test/java/com/wso2/openbanking/accelerator/consent/extensions/common/idempotency/IdempotencyValidatorTests.java

> This PR contains the fixes for issues identified in Idempotency QA testing
**Issue link:** **
**Doc Issue:** **
**Applicable Labels:** *OB 3.0.0*
------
6. [ x Have you verified the PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?
2. [ ] Verified tests …

Fixed Issue in idempotency validation for APIs without a payload

---

open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/JWTUtils.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/dcr/DCRExecutor.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/SignatureValidator.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/validationgroups/AttributeChecks.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/validationgroups/MandatoryChecks.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/validationgroups/SignatureCheck.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/validationgroups/ValidationOrder.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/validation/validationgroups/ValidityChecks.java

> Deprecate the old validationorder package and introduce a new package.
> Deprecate the old ```validateJWTSignature ``` method and keep the same method with the name ```isValidSignature ``` to avoid build failures.
**Issue link:** 
**Doc Issue:** 
**Applicable Labels:** *Accelerator*
------
8. [x] Have you followed secure coding standards in [WSO2 Secure …

Deprecate old package and method keeping the new ones to avoid build failures

---

open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java

> This PR fixes the issue of calling `consentCoreDAO.updateConsentMappingStatus()` in application deletion even when there are no consents for the particular application.
**Issue link:** *https://github.com/wso2/financial-open-banking/issues/81*
------
6. [ ] Have you verified the PR doesn't commit any keys, passwords, tokens, …

Fix unnecessary account mapping update in application deletion

---

open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/token/TokenFilter.java

> When a proxy is added to IS APIs through gateway, TLS is terminated at gateway and the Gateway transport certificate is passed to the IS. This causes client authentication failures. The certificate is added to the request as a header by GatewayClientAuthenticationHandler. This PR adds changes to the TokenFilter to prevent overriding that header if it is available.
**Issue link:** *https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/511*
------
3. [ ] Ran Findbugs plugin …

[OB3] Prevent overriding MTLS Cert Header at TokenFilter

---

react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/App.js
react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/servlet/OAuthCallbackServlet.java

> This PR fixes consent manager white screen issue and logout issue.
**Issue**: 
- https://github.com/wso2/financial-services-accelerator/issues/134
When the `consentmgr.war` is built from the open source accelerator repo and deployed, and go to `https://localhost:9446/consentmgr/` there is a white screen coming. 
This is due to an attempt to get an id_token to a user which is not initialized. This PR fixes this.
------
6. [X] Have you verified the PR doesn't commit any keys, passwords, tokens, usernames, or other …

Fixing consent manager white screen issue

---

open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-5.11.0-deployment.toml
open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-6.0.0-deployment.toml
open-banking-accelerator/accelerators/ob-is/repository/resources/wso2is-6.1.0-deployment.toml
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/token/TokenFilter.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/token/TokenFilterTest.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/token/util/TestConstants.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/token/validators/MTLSEnforcementValidatorTest.java

This PR contains an improvement to the accelerator to stop mandating the transport certificate for the token request. The transport certificate is mandated to bind the certificate to the access token using the "cnf" claim.
However to properly omit sending the transport the following configs also need to be added and must remove the MTLSEnforcementValidator like below:
```
#[[open_banking.identity.token_filter_validators]]
#class = "com.wso2.openbanking.accelerator.identity.token.validators.MTLSEnforcementValidator"
[[open_banking.identity.token_filter_validators]]
class = "com.wso2.openbanking.accelerator.identity.token.validators.MTLSCertificateValidator"
[[open_banking.identity.token_filter_validators]]
class = "com.wso2.openbanking.accelerator.identity.token.validators.SignatureAlgorith …
```

[OB3] Provide config for making transport cert optional for the token endpoint

---

open-banking-accelerator/accelerators/ob-apim/bin/configure.sh

> When running obam accelerator config.sh multiple times, `<sequence key="jsonConverter"/>` entry in `_cors_request_handler_.xml` is repeated. This PR fixes this.
**Issue link:** 
- https://github.com/wso2/financial-services-accelerator/issues/145
**Applicable Labels:** OB3 Accelerator
------
8. [ ] Have you followed secure coding standards in [WSO2 Secure …

Fix jsonConverter duplicate entry issue in configure.sh

---

open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/main/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/EventNotificationProducerService.java
open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/main/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationLoaderService.java
open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/main/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationSenderService.java
open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/main/java/com/wso2/openbanking/accelerator/event/notifications/service/util/EventNotificationServiceUtil.java
open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/test/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/EventNotificationProducerServiceTests.java
open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/test/java/com/wso2/openbanking/accelerator/event/notifications/service/realtime/service/RealtimeEventNotificationLoaderServiceTest.java
open-banking-accelerator/components/event-notifications/com.wso2.openbanking.accelerator.event.notifications.service/src/test/java/com/wso2/openbanking/accelerator/event/notifications/service/utils/EventNotificationTestUtils.java

This PR fixes the issues identified in real time notifications
**Issue link:**https://github.com/wso2/financial-services-accelerator/issues/148, https://github.com/wso2/financial-services-accelerator/issues/153, https://github.com/wso2/financial-services-accelerator/issues/154, https://github.com/wso2/financial-services-accelerator/issues/155, https://github.com/wso2/financial-services-accelerator/issues/168
**Doc Issue:**
------
6. …

Fix issues in realtime notification

---

open-banking-accelerator/accelerators/ob-is/carbon-home/repository/resources/conf/templates/repository/conf/open-banking.xml.j2
open-banking-accelerator/components/com.wso2.openbanking.accelerator.ciba/src/main/java/com.wso2.openbanking.accelerator.ciba/OBCIBARequestObjectValidationExtension.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.ciba/src/test/java/com/wso2/openbanking/accelerator/ciba/OBCIBARequestObjectValidationExtensionTest.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/config/OpenBankingConfigParser.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/constant/OpenBankingConstants.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/CarbonUtils.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/java/com/wso2/openbanking/accelerator/common/test/OBConfigParserTests.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/resources/open-banking.xml
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/auth/extensions/response/handler/OBCibaResponseTypeHandler.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/auth/extensions/response/validator/OBCibaResponseTypeValidator.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/auth/extensions/response/handler/OBCibaResponseTypeHandlerTest.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/resources/testng.xml
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/pom.xml
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/authorize/impl/CIBAConsentPersistStep.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/authorize/impl/CIBAWebAuthLinkConsentPersistStep.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/authorize/impl/DefaultConsentPersistStep.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/authorize/impl/DefaultConsentRetrievalStep.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/CIBAWebLinkAuthenticator.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/CIBAWebLinkAuthenticatorConstants.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/notification/CIBAWebLinkNotificationHandler.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/notification/provider/NotificationProvider.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/authenticator/weblink/notification/provider/SMSNotificationProvider.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/ConsentExtensionConstants.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/common/ConsentExtensionUtils.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/internal/ConsentExtensionsComponent.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/main/java/com/wso2/openbanking/accelerator/consent/extensions/internal/ConsentExtensionsDataHolder.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/test/java/com/wso2/openbanking/accelerator/consent/extensions/authorize/vrp/persistence/flow/ConsentPersistStepTests.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.extensions/src/test/java/com/wso2/openbanking/accelerator/consent/extensions/ciba/weblink/CIBAWebLinkAuthenticatorTests.java
pom.xml

This PR is to add the CIBA auth weblink based authenticator. Ref [1]
[1] Mail : ```Re: Invitation: CIAM POC and WSO2 Multi User Approval Clarifications```
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/128
**Doc Issue:** https://github.com/wso2/docs-open-banking/issues/900
------
7. [ ] Migration scripts …

[OB3] CIBA auth weblink authenticator 

---

open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/claims/RoleClaimProviderImpl.java
open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java
react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/common/Footer.jsx
react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/common/Nav.jsx
react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/detailedAgreementPage/KeyDatesInfo.jsx
react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/errorPage/ResponseError.jsx
react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/landing_page/AdvanceSearch.jsx
react-apps/self-care-portal/self-care-portal-frontend/accelerator/src/specConfigs/common.js
react-apps/self-care-portal/self-care-portal-frontend/package.json
react-apps/self-care-portal/src/main/java/com/wso2/openbanking/scp/webapp/servlet/OAuthCallbackServlet.java

This PR fixes multiple issues in consent manager portal.
**Related Issues:**
- https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/433
- https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/413
- https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/437
- https://github.com/wso2-enterprise/ob-compliance-toolkit-cds/issues/417
- https://github.com/wso2/financial-services-accelerator/issues/182
- https://github.com/wso2/financial-services-accelerator/issues/178
**Applicable Labels:** OB3 Accelerator
------
5. [X] Formatted …

Fix consent manager issues

---

open-banking-accelerator/components/consent-management/com.wso2.openbanking.accelerator.consent.mgt.service/src/main/java/com/wso2/openbanking/accelerator/consent/mgt/service/impl/ConsentCoreServiceImpl.java

> Tokens are not revoked after arrangement revoke request. Eventhough the token type is set as `refresh_token`, the access_token is passed to IS `revokeTokenByOAuthClient` method. This PR fixes this by passing `refresh_token`.
- https://github.com/wso2-enterprise/wso2-ob-internal/issues/898
**Applicable Labels:** CDS Toolkit
------
8. [ ] Have you followed secure …

Fix tokens not revoking issue

---

open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/model/PSD2RoleEnum.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/eidas/certificate/extractor/CertificateContent.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/main/java/com/wso2/openbanking/accelerator/common/util/eidas/certificate/extractor/CertificateContentExtractor.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.common/src/test/java/com/wso2/openbanking/accelerator/common/test/util/eidas/certificate/extractor/CertificateContentExtractorTest.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.gateway/src/main/java/com/wso2/openbanking/accelerator/gateway/executor/service/CertValidationService.java

- This PR adds a new getter and a setter to set/get roles and PSD2 roles (AISP, PISP, etc) in formats from the ```CertificateContent``` class. The relevant variable is initialized when extracting the certificate content from the ```extract()``` method of the ```CertificateContentExtractor``` class.
- The ```isRequiredRolesMatchWithScopes()``` method in ```CertValidationService``` class is changed to check for both ```psp``` and ```psd2``` roles when validating the roles.
- The unit tests are changed according to the above changes.
**Related Issue link:** 
https://github.com/wso2/financial-services-accelerator/issues/163
**Applicable Labels:** OB2
------
3. …

[OB3] Role extraction improvement - add support to extract both PSD2 and PSP roles from the certificate as needed

---

README.md

**Applicable Labels:** OB3
------
2. [ ] Documented test scenarios(link available in guides).
3. [ ] Written automation tests (link available in guides).
4. [ ] …

Add build notes to the README.md file for 3.0.0 branch

---

financial-services-accelerator/accelerators/fs-apim/bin/configure.ps1
financial-services-accelerator/accelerators/fs-apim/bin/configure.sh
financial-services-accelerator/accelerators/fs-apim/repository/conf/configure.properties
financial-services-accelerator/accelerators/fs-apim/repository/resources/wso2am-4.4.0-deployment.toml
financial-services-accelerator/accelerators/fs-is/bin/configure.ps1
financial-services-accelerator/accelerators/fs-is/bin/configure.sh
financial-services-accelerator/accelerators/fs-is/carbon-home/repository/conf/financial-services.xml
financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
financial-services-accelerator/accelerators/fs-is/repository/conf/configure.properties
financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml

> This PR allows configurating different super admins for each server. Configure scripts are changed to get the admin credentials from the configure.properties file and replace in relevant places.
------
6. [ ] Have you verified the PR doesn't commit any keys, passwords, tokens, usernames, or other …

[Accelerator 4] Configuring different super admins for each server

---

open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/auth/extensions/request/validator/FapiRequestObjectValidator.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/auth/extensions/request/validator/OBRequestObjectValidator.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/auth/extensions/request/validator/models/FapiRequestObject.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/auth/extensions/request/validator/models/OBRequestObject.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/common/annotations/validationorder/ValidationOrder.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/dcr/utils/ValidatorUtils.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/auth/extensions/request/validator/DefaultOBRequestObjectValidatorTest.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/auth/extensions/request/validator/FapiRequestObjectValidatorTest.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/auth/extensions/request/validator/ReqObjectTestDataProvider.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/utils/TestUtils.java
pom.xml

>  This PR fix issue in FAPI test suite when sending request object without exp claim. 
> Integration test PR - https://github.com/wso2-enterprise/bfsi-test-resources/pull/69
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/252
**Applicable Labels:** *OB 3.0.0*
------
7. [ ] …

[OB3] Fix issue in FAPI test suite when sending request object without exp claim

---

financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
financial-services-accelerator/accelerators/fs-is/repository/resources/wso2is-7.0.0-deployment.toml
financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigParser.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigurationService.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/config/FinancialServicesConfigurationServiceImpl.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/constant/FinancialServicesConstants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/test/resources/repository/conf/financial-services.xml
financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/pom.xml
financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/auth/extensions/response/validator/FSHybridResponseTypeValidator.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/cache/JwtJtiCache.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/dcr/cache/JwtJtiCacheKey.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/internal/IdentityExtensionsDataHolder.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonConstants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.identity.extensions/src/main/java/org/wso2/financial/services/accelerator/identity/extensions/util/IdentityCommonUtils.java

[Accelerator 4] Adding JTI cache and DCR configurations

---

open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/PushAuthRequestValidator.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/main/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/util/PushAuthRequestValidatorUtils.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.identity/src/test/java/com/wso2/openbanking/accelerator/identity/push/auth/extension/request/validator/PushAuthRequestValidatorTest.java

**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/384
**Doc Issue:**
------
6. [X] Have you verify the PR does't commit any keys, passwords, tokens, usernames, or other secrets?
8. [X] Have you followed secure coding standards in [WSO2 Secure Engineering Guidelines](http://wso2.com/technical-reports/wso2-secure-engineering-guidelines)?
2. [ ] …

[OB3] Remove PAR endpoint additional parameter validation

---

financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/dao/impl/ConsentCoreDAOTests.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.dao/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/dao/util/ConsentMgtDAOTestData.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/DefaultConsentPersistStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/DefaultConsentRetrievalStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/util/ConsentAuthorizeUtil.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionConstants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/DefaultConsentPersistStepTest.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/DefaultConsentRetrievalStepTest.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/ExternalAPIConsentRetrievalStepTest.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/util/TestConstants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.service/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/service/util/ConsentMgtServiceTestData.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.event.notifications.service/src/test/java/org/wso2/financial/services/accelerator/event/notifications/service/util/EventNotificationTestUtils.java

> This PR adds changes required to demonstrate a non initiated consent authorization flow (eg: CDS consent authorization flow) without configuring any extension.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/484*
------
6. [ ] Have you verified the PR doesn't commit any keys, passwords, tokens, …

[Accelerator 4] Add default non initiated consent flow 

---

financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionUtils.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/DefaultConsentManageHandler.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/utils/ConsentManageConstants.java

> In default consent manage handler there is a validation in consent retrieval and revoke flows that checks whether request-uri matches with the consent type. This PR adds a fix to ignore that validation when the consent API extension is enabled. If the extension is enabled, such validations should be done in the toolkit.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/462*
------
4. [ ] Ran …

[OB4 - M4] Exclude consent type and path matching validation in extensions

---

financial-services-accelerator/accelerators/fs-apim/pom.xml
financial-services-accelerator/accelerators/fs-is/pom.xml

> This PR copies the accelerator artifacts to the accelerator product since previously there was a file name mismatch. The fix avoids copying the jar names that end with "javadoc"
------
7. [ ] …

[Accelerator-4] Fix for copying required accelerator artifacts

---

financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentPersistStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentRetrievalStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionConstants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/utils/ExternalAPIConsentManageUtilsTest.java

> This PR adds changes required to update consent status on consent authorize error scenarios. The consent status will be updated to the "newConsentStatus" filed sent in the "data" json of the error response.
------
7. [ ] …

[OB4] Change to update consent status on authorize error

---

financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/DefaultConsentPersistStep.java

> This PR adds changes to persist commonAuthId in default consent persist step for non initiated consents (similar to CDS authorization flow). This is done to find the consent later in the authorization flow.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/484*
------
6. [ ] Have you verified the …

[OB4] Persist commonAuthId in default consent persist step

---

financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentRetrievalStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/model/ExternalAPIPreConsentAuthorizeRequestDTO.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/model/ExternalAPIConsentResourceRequestDTO.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/ExternalAPIConsentRetrievalStepTest.java

> This PR adds a change to send the consent file in the /populate-consent-authorize-screen extension request if a file is available.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/560*
------ …

[OB4] Add consent file content to consent authorize extension API request

---

financial-services-accelerator/accelerators/fs-is/repository/resources/apis/accelerator-extensions-v1.yaml
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/DefaultConsentPersistStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/DefaultConsentRetrievalStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentPersistStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/impl/ExternalAPIConsentRetrievalStep.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/model/ExternalAPIPreConsentPersistRequestDTO.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ConsentExtensionConstants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/ExternalAPIConsentPersistStepTest.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/test/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/common/ExternalAPIUtilTest.java

> This PR contains following changes:
- Add request object parameters to /persist-authorized-consent extension request
- If request object parameters are not present, add scope from query parameters
- Introduce a proper structure to userGrantedData object in /persist-authorized-consent extension request
- Fix issues occurred when only the /persist-authorized-consent extension is enabled
------
4. [x] Ran FindSecurityBugs plugin and …

[OB4] Add request parameters to consent persist extension

---

financial-services-accelerator/components/org.wso2.financial.services.accelerator.common/src/main/java/org/wso2/financial/services/accelerator/common/util/ServiceExtensionUtils.java

> This PR adds a fix to make the object mapper variable a class variable. At present an ObjectMapper instace is created per extension api request which hinders performance at high load.
------
7. [ ] Migration scripts …

[OB4][Perf] Make objectMapper a class variable

---

financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/DefaultConsentManageHandler.java

> This PR adds consent operation enum to consent exceptions occurred in file upload and retrieval. This is used in returning an error with customized format in the toolkit.
**Issue link:** *https://github.com/wso2/financial-services-accelerator/issues/542*
------
6. [ ] Have you verified the PR doesn't commit any keys, …

[OB4] Add consent operation enum to file upload and retrieval errors

---

financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/java/org/wso2/financial/services/accelerator/authentication/endpoint/FSConsentConfirmServlet.java
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/java/org/wso2/financial/services/accelerator/authentication/endpoint/FSConsentServlet.java

> This fixes a possible SSRF attack where the session data key is obtained from outside, it is validated against a UUID format to verify if there are no unexpected input provided by the users
------
6. [x] Have you verified the PR doesn't commit any keys, passwords, tokens, usernames, or other …

[Accelerator 4] Validate session data key to check if it as a valid UUID

---

open-banking-accelerator/components/com.wso2.openbanking.accelerator.keymanager/src/main/java/com/wso2/openbanking/accelerator/keymanager/OBKeyManagerConstants.java
open-banking-accelerator/components/com.wso2.openbanking.accelerator.keymanager/src/main/java/com/wso2/openbanking/accelerator/keymanager/OBKeyManagerImpl.java

- This PR makes the SP property ```useUserIdForDefaultSubject``` as ```false``` to make username the default subject identifier across IS 6.0.0 and IS 6.1.0. This property is not used when the OB solution is deployed on IS 5.11.0.
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/289
**Doc Issue:** : Needs to remove the steps mentioned in the documentation to add the subject claim URL.
- https://github.com/wso2/docs-open-banking/issues/915
- https://github.com/wso2/docs-open-banking/issues/914
**Applicable Labels:** *OB3 Accelerator*
------
4. [x] Ran FindSecurityBugs plugin and verified …

Set username as the default subject identifier

---

.github/workflows/log-pr-comment-analyzer.yml
.github/workflows/pr-reviewer-for-logs.yml

This will introduce new git action on PR merge to analyze the status of the added comments by AI Log Agent
=========================
This pull request introduces a new GitHub Actions workflow to notify an AI log agent when a pull request is merged and simplifies an existing workflow for PR review by removing unused variables. Below are the key changes:
* Added `.github/workflows/log-pr-comment-analyzer.yml` to notify an AI log agent when a pull request is merged into the `main` branch. This includes a job to fetch PR details and another to invoke the AI log agent using the `prUrl` of the merged PR.
* Removed unused `reviewEndpoint` and `tokenUrl` inputs from the `call-template` job in `.github/workflows/pr-reviewer-for-logs.yml`, streamlining the workflow configuration.

Add log PR comment analyzer

---

financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/impl/DefaultConsentManageHandler.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/manage/utils/ConsentManageUtils.java

> This PR uses a regex match to identify the consent id from a request path and uses it for retrieval, revocation, file upload and file retrieval. It extracts the first UUID in the resource path as consent id.
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/622
------
6. [x] Have you verified the …

Using regex to find consent ID from resource path

---

financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/util/ConsentAuthorizeUtil.java

> This PR changes the default flow's account display name of payment and CoF consents to the account's identification (in consent authorization).
------
7. [ ] Migration scripts written (if …

Set account identification as display name for payments and CoF

---

financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authservlet/utils/Constants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authservlet/utils/Utils.java
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/resources/org/wso2/financial/services/accelerator/authentication/endpoint/i18n.properties
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/webapp/includes/confirmation-dialogue.jsp

> This PR fixes the confirmation button's text on the consent authorization page.
**Issue link:** https://github.com/wso2/financial-services-accelerator/issues/785
------
8. …

Correct Confirmation Button Text from 'OK' to 'Confirm'.

---

financial-services-accelerator/accelerators/fs-is/carbon-home/repository/resources/conf/templates/repository/conf/financial-services.xml.j2
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authorize/util/ConsentAuthorizeConstants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authservlet/utils/Constants.java
financial-services-accelerator/components/org.wso2.financial.services.accelerator.consent.mgt.extensions/src/main/java/org/wso2/financial/services/accelerator/consent/mgt/extensions/authservlet/utils/Utils.java
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/java/org/wso2/financial/services/accelerator/authentication/endpoint/FSConsentServlet.java
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/resources/org/wso2/financial/services/accelerator/authentication/endpoint/i18n.properties
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/webapp/WEB-INF/web.xml
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/webapp/fs_default.jsp
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/webapp/fs_default_account_selection.jsp
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/webapp/includes/selected-accounts.jsp
financial-services-accelerator/internal-webapps/org.wso2.financial.services.accelerator.authentication.endpoint/src/main/webapp/js/auth-functions.js

This PR contains the feature for segregating the account selection page from the consent confirmation page using a json response attribute coming from the https://ob.docs.wso2.com/en/latest/develop/openapi-consent-management-authorize/#openapi-extensions service extension.
The attribute "handleAccountSelectionSeparately" has been introduced, if true, it displays the accounts in a separate page else it displays the accounts along with the other consent data then the consent can be confirmed from the same page.
When a response like the following is sent for the populate-consent-authorize-screen service extension:
```
{
"responseId": "9578b3dc-ddc8-454e-8998-ed9472448810",
"status": "SUCCESS",
"data": {
"consentData": {
"initiatedAccountsForConsent": [],
"allowMultipleAccounts": true, …
```

[OB4] Account selection page segregation feature
